#ifndef IRODS_API_PLUGIN_BULKREG_CONSTANTS_HPP
#define IRODS_API_PLUGIN_BULKREG_CONSTANTS_HPP

namespace irods {
    const std::string DATABASE_OP_BULKREG{"database_bulkreg"};
}
#endif // IRODS_API_PLUGIN_BULKREG_CONSTANTS_HPP
